package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"
	"token-transfer-api/db"
	"token-transfer-api/models"

	"gorm.io/gorm/clause"
)

// Transfer is the resolver for the transfer field.
func (r *mutationResolver) Transfer(ctx context.Context, fromAddress string, toAddress string, amount int32) (int32, error) {
	if amount < 0 {
		return 0, fmt.Errorf("amount below 0")
	}
	tx := db.DB.Begin()
	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
		}
	}()

	if err := tx.Error; err != nil {
		return 0, err
	}
	var from_wallet models.Wallet
	err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).Where("address = ?", fromAddress).First(&from_wallet).Error
	if err != nil {
		tx.Rollback()
		return 0, err
	}
	var to_wallet models.Wallet
	err = tx.Where("address = ?", toAddress).First(&to_wallet).Error
	if err != nil {
		to_wallet = models.Wallet{Address: toAddress, Balance: 0}
		if err := tx.Create(&to_wallet).Error; err != nil {
			tx.Rollback()
			return from_wallet.Balance, err
		}
	}
	err = tx.Clauses(clause.Locking{Strength: "UPDATE"}).Where("address = ?", toAddress).First(&to_wallet).Error
	if err != nil {
		tx.Rollback()
		return 0, err
	}

	if from_wallet.Balance < amount {
		tx.Rollback()
		return from_wallet.Balance, fmt.Errorf("insufficient balance")
	}

	from_wallet.Balance -= amount
	to_wallet.Balance += amount

	if tx.Save(&from_wallet).Error != nil || tx.Save(&to_wallet).Error != nil {
		tx.Rollback()
		return from_wallet.Balance + amount, fmt.Errorf("saving error")
	}

	if err := tx.Commit().Error; err != nil {
		tx.Rollback()
		return 0, err
	}

	return from_wallet.Balance, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
